# Configuration des serveurs
servers:
  proxmox:
    name: "LM150g6"
    node_name: "pve" # Nom du nœud Proxmox
    ipv4: "192.168.1.XXX"
    mac_address: "00:00:00:00:00:00"
    wake_on_lan_enabled: true # Activé pour tester le démarrage
    # Configuration API REST
    api_url: "https://192.168.1.245:8006/api2/json"
    api_token_id: "xxxxxx@pam!xxxxxxxxxxxxx"
    api_token_secret: "0000xxx0-azer-ty00-xxx0-0000000000"
    # Configuration SSH (désactivée)
    ssh_user: "xxxx"
    ssh_key_path: "C:\\Users\\...\\pve-key" # Chemin local Windows
    # Pour Docker : utiliser "./keys/proxmox_ssh_key"
    web_interface: "https://192.168.1.245:8006"

  minecraft:
    name: "Minecraft Server"
    ipv4: "192.168.1.XXX" # IP du serveur Minecraft
    port: 25XXX
    timeout: 5 # Timeout pour test de connectivité
    startup_delay: 380 # Délai après démarrage Proxmox avant test Minecraft (augmenté pour stabilité)
